export const Users = [
    {
        id: 1,
        profilePicture: "person/1.jpeg",
        username: "First Guy",
    },
    {
        id: 2,
        profilePicture: "person/2.jpeg",
        username: "Second Guy",
    },
    {
        id: 3,
        profilePicture: "person/3.jpeg",
        username: "Third Guy",
    },
    {
        id: 4,
        profilePicture: "person/4.jpeg",
        username: "Fourth Guy",
    },
    {
        id: 5,
        profilePicture: "person/5.jpeg",
        username: "Fifth Guy",
    },
    {
        id: 6,
        profilePicture: "person/6.jpeg",
        username: "Six Guy",
    },
    {
        id: 7,
        profilePicture: "person/7.jpeg",
        username: "Seventh Guy",
    },
    {
        id: 8,
        profilePicture: "person/8.jpeg",
        username: "Eighth Guy",
    },
    {
        id: 9,
        profilePicture: "person/9.jpeg",
        username: "Ninth Guy",
    },
    {
        id: 10,
        profilePicture: "person/10.jpeg",
        username: "Tenth Guy",
    },
]

export const Posts = [
    {
        id: 1,
        desc: "Though the world be cruel, my life is magic",
        photo: "post/1.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "post/2.jpeg",
        date: "25 mins ago",
        userId: 2,
        like: 2,
        comment: 4,
    },
    {
        id: 3,
        desc: "YOLO",
        photo: "post/3.jpeg",
        date: "I hour ago",
        userId: 3,
        like: 10,
        comment: 3,
    },
    {
        id: 4,
        desc: "Push past it!",
        photo: "post/4.jpeg",
        date: "5 mins ago",
        userId: 4,
        like: 100,
        comment: 90,
    },
    {
        id: 5,
        desc: "It's happening!",
        photo: "post/5.jpeg",
        date: "5 mins ago",
        userId: 5,
        like: 32,
        comment: 9,
    },
    {
        id: 6,
        desc: "The blessings grow!",
        photo: "post/6.jpeg",
        date: "5 mins ago",
        userId: 6,
        like: 32,
        comment: 9,
    },
    {
        id: 7,
        desc: "I stand in my power",
        photo: "post/7.jpeg",
        date: "5 mins ago",
        userId: 7,
        like: 32,
        comment: 9,
    },
    {
        id: 8,
        desc: "The trees continue to rise",
        photo: "post/8.jpeg",
        date: "5 mins ago",
        userId: 8,
        like: 32,
        comment: 9,
    },
    {
        id: 9,
        desc: "Let's get this bread!",
        photo: "post/9.jpeg",
        date: "5 mins ago",
        userId: 9,
        like: 32,
        comment: 9,
    },
    {
        id: 10,
        desc: "I am worthy",
        photo: "post/10.jpeg",
        date: "5 mins ago",
        userId: 10,
        like: 32,
        comment: 9,
    },
]